name: Deploy Frontend to NCP

on:
  push:
    branches: [main] # 또는 main 브랜치라면 수정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_SSH_KEY }}
          port: 22
          script: |
            cd /root/milo-fe
            git pull origin main
            npm install
            npm run build
            docker-compose -f /root/docker-compose.yml down
            docker-compose -f /root/docker-compose.yml up -d --build
